[project]
name = "fcf-to-prices-relation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "simfin>=1.0.1",
]
